### PR TITLE
Very Many Enhancements & Bugfixes

### LINKED ISSUE #99: (At least) one player's username appears twice - 201.5.2
### Description
Simple. One person's (potentially others' as well, haven't checked) username appears twice in the chat, in the same line, before their chat message. This does not happen to someone else's username who was on the server.

### How to reproduce
1. Install chat patches
2. Join a server
3. Have different people send messages in the chat
4. Hopefully one of them will have two usernames so you can reproduce the issue

### Expected result
For the person in question to only have one username before their chat message

### Log file link
[latest.log](https://mclo.gs/gt4kOuK)

### Specs and Details
Required information:
- Windows 11 Home
- Chat Patches 201.5.2
- Quilt Loader 0.19.2 and QFAPI 7.0.5 with QSL 6.0.4
- YetAnotherConfigLib 3.0.3 and Mod Menu 7.1.0
- Mods:
image
image
image
image

Optional but suggested information:
- [chatpatches.json](https://mclo.gs/mODkIeh)
- [chatlog.json](https://mclo.gs/03HUmrl)

### Additional context
Screenshot 2023-07-13 170450

### LINKED ISSUE #101: Subcommand selection (1.20.1)
### Description

Subcommand select with ArrowUp is not working

https://discord.com/channels/1077285607375638529/1077297192659861686/1129438714855165952
https://discord.com/channels/1077285607375638529/1077297192659861686/1129442978843336822

### PR DESCRIPTION
**Pull request by hexadecimal233**
Fixes #101
Fix autocompletion up key shows the message history instead of the prev suggestion
Fixed elements added by other mods (like no chat reports) are not clickable
Fix Tweakeroo message draft not working
lazydfu no more needed
Created a new class for search button
Add Ignore hide message packet toggle
Fix chat focus bug again
Partially fixed #99 by disabling player name format when format is "<$>"

### CODE REVIEW

**Comment by mrbuilder1961** [comment]
WOW! i never expected anyone else to actually contribute code changes to the project, thank you!! i'm not going to merge it just yet bc i want to look it over thoroughly and make sure it's formatted the same and it all works.

i really really appreciate it, and if you join the discord let me know so i can give you your contribution role!

**Comment by mrbuilder1961** [comment]
also could you log your changes in `changelog.md`?

**Comment by hexadecimal233** [comment]
Just updated the changelog and should be able to merge it :P
Also the cps$ can be removed, mixin will add them

**Comment by mrbuilder1961** [comment]
yeah i realized the mixin thing way after i alr added them so i just kept them anyway.

btw this is looking to be almost done, i'm just trying out a few things on my end to verify it's all working smoothly. i might have to exclude a couple parts from being approved (if i can even do that) just bc i'm already implementing a few things you did here.

thanks again!

**Comment by mrbuilder1961** [comment]
oh also idk how to do this, but do you think you could give me write permissions on your fork just so i could do a couple style/writing changes? i'll leave the important logic and code to requests 😄

**Comment by hexadecimal233** [comment]
I have added you to the collaborators and these changes should be fine.

**Pull request merged**
