### PR TITLE
Add chat height configuration option

### PR DESCRIPTION
**Pull request by DylanKeir**
Hi there,

I'm not sure about other resolution monitors, but I'm running a 1440p 21:9 ultrawide monitor and the chat box is rather small, the 180px chat height setting built in is very small for me. I've been running a private fork with a custom chat height option for 1.20.1 but since I'm updating my server to 1.21, I thought I'd PR the updated patch to the main repo.

Please let me know if there's anything that needs changing, do note that I only updated the English lang files since that's the only language I speak.

Thanks,
Dylan.

### CODE REVIEW

**Comment by mrbuilder1961** [comment]
this is awesome, i appreciate the contribution! the only thing missing is an entry in the `changelog.md` file, could you add a line detailing the option? tysm

**Comment by DylanKeir** [comment]
I've gone ahead and bumped the version as well as added the changelog entry as request. Let me know if there's anything else.

**Comment by mrbuilder1961** [comment]
whoops sorry to be misleading, you can just leave the version as 210.6.6 because i haven't published that one yet. thanks!!

**Comment by DylanKeir** [comment]
Hey, bit late but gone ahead and done that.

**Pull request merged**
